services:
  - type: web
    name: text-sum-api
    env: python
    region: frankfurt
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HUGGINGFACE_TOKEN
        value: your_token_here # Set this in Render.com dashboard
    healthCheckPath: /health